### ISSUE TITLE
Separate the "<<<<" and ">>>>" lines into a separate log file

### ISSUE THREAD

**Issue by bontchev** [huuck/ADBHoney#10]
Currently these lines, while useful for debugging what is actually happening, clutter the log file and it is hard to see what the attacker is really doing. I propose that these are written to a separate .log file (the creation of which should be optional and controlled by the config file), while the main report is in JSON format. See also issues #2 and #7.

**Comment by bontchev** [comment]
Implemented the behavior we have discussed in pull request #22.

**Comment by huuck** [comment]
Looks good, closing
