### ISSUE TITLE
Make it easy to create output plug-ins

### ISSUE THREAD

**Issue by bontchev** [huuck/ADBHoney#11]
We have already discussed elsewhere the need to log in JSON files. But this should be generalized further. For instance, we (our Lab) need the honeypot to log data to a MySQL database. Many others use ElasticSearch for collecting data from their honeypots.

It should be easy to create separate plug-ins for adding logging into the proper kind of database, where most of the relevant information is concentrated in the plug-in and doesn't mess up the whole program of the honeypot. The main program of the honeypot should just read the config file for enabled plug-ins and then call the Python module of the corresponding plug-in from a directory where they all reside.

I know of somebody who has already modified this honeypot to collect data to an ElasticSeach database, but I don't know how exactly their code works and I'd like to have a general concept of plug-ins before adding their code here.

**Comment by huuck** [comment]
Check out the latest merge, @pieterbork added a lot of cool stuff
