### ISSUE TITLE
Question: Is it OK to modify the current default behavior of the honeypot?

### ISSUE THREAD

**Issue by bontchev** [huuck/ADBHoney#20]
While my colleague will be working on making the honeypot configurable with a config file (issue #7), I am thinking of implementing some command-line options that would make it do what I need. My problem, however, is that if I do this, by default the honeypot will behave differently from the way it does now. Here is what I mean.

1) I can solve issue #10 by implementing a command-line option that specifies a log file for the debug lines (the lines starting with ">>>>" or "<<<<"). But I want this output _not_ to be generated by default (as it currently is), in order not to clutter the log. Like, I'd rather implement a `--debug` option that turns this output on. Is this OK?

2) I would like to change the look of the "normal" (non-debug) lines, so that they output human-readable timestamps, just the IP (instead of the whole `addr` tuple), and maybe more readable information messages. Again, this would mean that the output would look differently than it already does - possibly messing up the job of people who are processing the currently generated logs. Is this OK?

3) I am thinking of starting to implement JSON logging (not as an output plug-in for now) - issue #2 - again with a command-line option specifying the JSON log file. Should I start working in this direction - or is anyone already working on a better solution?

**Comment by huuck** [comment]
I would say that it's a go for all 3 options. I would like to keep UNIX timestamps for JSON logging though (easier to parse), while still having human readable dates for normal logging.

Kindest regards,
Gabriel

**Comment by bontchev** [comment]
I'd like to have human-readable timestamps in the JSON log too, so I have decided to put both kinds of timestamps there (`timestamp` and `unixtime`). I have implemented what we're discussing here in pull request #22. Closing this issue now, since my question was answered.
