### ISSUE TITLE
Save only unique payloads

### ISSUE THREAD

**Issue by fe7ch** [huuck/ADBHoney#3]
When a payload is saved it should be hashed if it's already exists it's safe to delete the new file.

So the problem at this moment is the fact, that adbhoney overwrites the file everytime that updates creation time of the file.

**Comment by fe7ch** [comment]
@huuck one line fix is ready (#6)

**Comment by bontchev** [comment]
The current solution has a small problem - if the file already exists, file transfer is not logged. Could you please move the logging operators before the statement that checks whether the file exists?
