### ISSUE TITLE
Create .gitignore file(s)

### ISSUE THREAD

**Issue by bontchev** [huuck/ADBHoney#8]
We should add at least one `.gitignore` file to the repository, so that when the honeypot downloads samples and creates log files they don't mess up git. Eventually, they should be in their own directory (one for samples, another for logs, etc.) and each such directory should have its own `.gitignore` file.

**Comment by fe7ch** [comment]
You can pass the folder for payloads via `--dlfolder` argument. There is a `dl` folder ready with .gitignore in it. Also a folder for logs is available.

**Comment by bontchev** [comment]
I am working on additional command-line options for this purpose. OK, I'll use `--dfolder` for specifying the download directory. Should `dl` be the default? Or should the default be the current directory, as it is now?

Any suggestion what to use as an option for specifying the logs? I'd rather specify a full file path instead of just a directory. How about `--logfile` for normal log and `--jsonlog` for the JSON log? If the first one is empty, logging goes to `stdout`; if the second one is empty, no JSON log is created. If the `--debug` option is specified, the current ">>>>" and "<<<<" lines will be put in the normal log, otherwise they won't be output at all. Does this sound acceptable?

**Comment by fe7ch** [comment]
>Should dl be the default? Or should the default be the current directory, as it is now?

I would prefer to `dl` be the default, but I haven't changed it in order to don't break backward compatibility for users, who blindly pull from master to update.

>Does this sound acceptable?

Yep, it sounds good to me.

**Comment by bontchev** [comment]
When to honeypot is run, `protocol.py` is compiled to `protocol.pyc`. Added `*.pyc` to `.gitignore`, so that git isn't annoyed by the additional file. Pull request #21.
