### ISSUE TITLE
Binary garbage after "file:SEND"

### ISSUE THREAD

**Issue by bontchev** [huuck/ADBHoney#9]
I've noticed in my logs that reports that contain "file:SEND" contain some kind of binary garbage (4 bytes, I think) immediately after the "SEND". It's not the length of the file. I'm not sure what it is, and it might even be fixed already (e.g., if it is the contents of the uninitialized `filename` variable) but it probably needs some looking into.

**Comment by huuck** [comment]
it only happens for some packets. It's not from the uninitialized filename, somebody needs to extract the contents of the filename for certain packet structures (or at least do a ascii encoding with ignoring non standard characters)

**Comment by huuck** [comment]
Fixed in the latest release.
